export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

// Activity Feed
export const ACTIVITY_SUCCESS = "ACTIVITY_SUCCESS";
export const ACTIVITY_FAIL = "ACTIVITY_FAIL";

export const SAVE_ACTIVITY_SUCCESS = "SAVE_ACTIVITY_SUCCESS";
export const SAVE_ACTIVITY_FAIL = "SAVE_ACTIVITY_FAIL";

export const UNSAVE_ACTIVITY_SUCCESS = "UNSAVE_ACTIVITY_SUCCESS";
export const UNSAVE_ACTIVITY_FAIL = "UNSAVE_ACTIVITY_FAIL";

export const HIDE_ACTIVITY_SUCCESS = "HIDE_ACTIVITY_SUCCESS";
export const HIDE_ACTIVITY_FAIL = "HIDE_ACTIVITY_FAIL";

export const UNHIDE_ACTIVITY_SUCCESS = "UNHIDE_ACTIVITY_SUCCESS";
export const UNHIDE_ACTIVITY_FAIL = "UNHIDE_ACTIVITY_FAIL";

export const DELETE_FEED = "DELETE_FEED";

export const ENABLE_FEED_SUCCESS = "ENABLE_FEED_SUCSESS";
export const ENABLE_FEED_FAIL = "ENABLE_FEED_FAIL";

export const DISABLE_FEED_SUCCESS = "DISABLE_FEED_SUCCESS";
export const DISABLE_FEED_FAIL = "DISABLE_FEED_FAIL";

// Member
export const FRIEND_REQUEST_SUCCESS = "FRIEND_REQUEST_SUCCESS";
export const FRIEND_REQUEST_FAIL = "FRIEND_REQUEST_FAIL";

export const ADD_FRIEND_SUCCESS = "ADD_FRIEND_SUCCESS";
export const ADD_FRIEND_FAIL = "ADD_FRIEND_FAIL";

export const IGNORE_FRIEND_SUCCESS = "IGNORE_FRIEND_SUCCESS";
export const IGNORE_FRIEND_FAIL = "IGNORE_FRIEND_FAIL";

export const MEMBER_VIEW = "MEMBER_VIEW";

export const PROFILE_INFO = "PROFILE_INFO";

export const USER_FRIEND = "USER_FRIEND";

export const USER_ALBUM = "USER_ALBUM";

export const USER_BLOG = "USER_BLOG";

export const USER_VIDEO = "USER_VIDEO";

export const USER_MUSIC = "USER_MUSIC";

export const BROWSE_MEMBER = "BROWSE_MEMBER";

// Album
export const CREATE_ALBUM_SUCCESS = "CREATE_ALBUM_SUCCESS";
export const CREATE_ALBUM_FAIL = "CREATE_ALBUM_FAIL";

export const DELETE_ALBUM = "DELETE_ALBUM";

export const BROWSE_ALBUM = "BROWSE_ALBUM";

export const BROWSE_ALBUM_PHOTOS = "BROWSE_ALBUM_PHOTOS ";

export const ALBUM_CATEGORY = "ALBUM_CATEGORY";

export const ALBUM_VIEW = "ALBUM_VIEW";

export const MY_ALBUM = "MY_ALBUM";

export const SEARCH_ALBUM = "SEARCH_ALBUM";

export const ALBUM_COMMENT = "ALBUM_COMMENT";

// Group
export const CREATE_GROUP_SUCCESS = "CREATE_GROUP_SUCCESS";
export const CREATE_GROUP_FAIL = "CREATE_GROUP_FAIL";

export const DELETE_GROUP = "DELETE_GROUP";

export const MENU = "MENU";

export const BROWSE_FEATURE = "BROWSE_FEATURE";

export const BROWSE_GROUP_ALBUM = "BROWSE_GROUP_ALBUM";

export const GROUP_CATAGORY = "GROUP_CATAGORY";

export const GROUP_INFO = "GROUP_INFO";

export const GROUP_ALBUM = "GROUP_ALBUM";

export const GROUP_MEMBERS = "GROUP_MEMBERS";

// Messages
export const SENT_MESSAGE_SUCCESS = "SENT_MESSAGE_SUCCESS";
export const SENT_MESSAGE_FAIL = "SENT_MESSAGE_FAIL";

export const INBOX_MESSAGE = "INBOX_MESSAGE";

export const VIEW_MESSAGE = "VIEW_MESSAGE";

// Notification
export const NOTIFICATION_LIST = "NOTIFICATION_LIST";

export const MARK_NOTIFICATION_SUCCESS = "MARK_NOTIFICATION_SUCCESS";
export const MARK_NOTIFICATION_FAIL = "MARK_NOTIFICATION_FAIL";

// Status Box
export const VALIDATE_VIDEO_SUCCESS = "VALIDATE_VIDEO_SUCCESS";
export const VALIDATE_VIDEO_FAIL = "VALIDATE_VIDEO_FAIL";

export const POST_STATUS_SUCCESS = "POST_STATUS_SUCCESS";
export const POST_STATUS_FAIL = "POST_STATUS_FAIL";

// Videos
export const BROWSE_VIDEO = "BROWSE_VIDEO";

export const VIDEO_COMMENT_SUCCESS = "VIDEO_COMMENT_SUCCESS";
export const VIDEO_COMMENT_FAIL = "VIDEO_COMMENT_FAIL";

export const VIEW_VIDEO = "VIEW_VIDEO";

export const LIKE_VIDEO_SUCCESS = "LIKE_VIDEO_SUCCESS";
export const UNLIKE_VIDEO_FAIL = "UNLIKE_VIDEO_FAIL";

export const UNLIKE_VIDEO_SUCCESS = "UNLIKE_VIDEO_SUCCESS";
export const LIKE_VIDEO_FAIL = "LIKE_VIDEO_FAIL";

export const FAVOURITE_VIDEO_SUCCESS = "FAVOURITE_VIDEO_SUCCESS";
export const FAVOURITE_VIDEO_FAIL = "FAVOURITE_VIDEO_FAIL";

export const WATCH_VIDEO_LATER_SUCCESS = "WATCH_VIDEO_LATER_SUCCESS";
export const WATCH_VIDEO_LATER_FAIL = "WATCH_VIDEO_LATER_FAIL";

export const ADD_TO_PLAYLIST_VIDEO_SUCCESS = "ADD_TO_PLAYLIST_VIDEO_SUCCESS";
export const ADD_TO_PLAYLIST_VIDEO_FAIL = "ADD_TO_PLAYLIST_VIDEO_FAIL";

export const SEARCH_VIDEO = "SEARCH_VIDEO";

export const DELETE_VIDEO = "DELETE_VIDEO";

export const EDIT_VIDEO_SUCCESS = "EDIT_VIDEO_SUCCESS";
export const EDIT_VIDEO_FAIL = "EDIT_VIDEO_FAIL";

export const CREATE_VIDEO_SUCCESS = "CREATE_VIDEO_SUCCESS";
export const CREATE_VIDEO_FAIL = "CREATE_VIDEO_FAIL";
// Channel Videos
export const VIEW_CHANNEL_VIDEO = "VIEW_CHANNEL_VIDEO";

export const CHANNEL_VIDEO_COMMENT_SUCCESS = "CHANNEL_VIDEO_COMMENT_SUCCESS";
export const CHANNEL_VIDEO_COMMENT_FAIL = "CHANNEL_VIDEO_COMMENT_FAIL";

export const CHANNEL_VIDEO_COMPOSER = "CHANNEL_VIDEO_COMPOSER";

export const CHANNEL_VIDEO_FEED = "CHANNEL_VIDEO_FEED";

export const BROWSE_CHANNEL_VIDEO = "BROWSE_CHANNEL_VIDEO";

export const RATE_CHANNEL_SUCCESS = "RATE_CHANNEL_SUCCESS";
export const RATE_CHANNEL_FAIL = "RATE_CHANNEL_FAIL";

export const CHANNEL_VIDEOS = "CHANNEL_VIDEOS";

export const DELETE_CHANNEL_VIDEO = "DELETE_CHANNEL_VIDEO";

export const CHANNEL_INFO = "CHANNEL_INFO";

export const CHANNEL_PHOTOS = "CHANNEL_PHOTOS";

export const CHANNEL_COMMENT = "CHANNEL_COMMENT";

export const EDIT_CHANNEL_SUCCESS = "EDIT_CHANNEL_SUCCESS";
export const EDIT_CHANNEL_FAIL = "EDIT_CHANNEL_FAIL";

export const FOLLOW_CHANNEL = "FOLLOW_CHANNEL";

export const LIKE_CHANNEL_SUCCESS = "LIKE_CHANNEL_SUCCESS";
export const LIKE_CHANNEL_FAIL = "LIKE_CHANNEL_FAIL";

export const UNLIKE_CHANNEL_SUCCESS = "UNLIKE_CHANNEL_SUCCESS";
export const UNLIKE_CHANNEL_FAIL = "UNLIKE_CHANNEL_FAIL";

export const FAVOURITE_CHANNEL_SUCCESS = "FAVOURITE_CHANNEL_SUCCESS";
export const FAVOURITE_CHANNEL_FAIL = "FAVOURITE_CHANNEL_FAIL";

export const DELETE_CHANNEL = "DELETE_CHANNEL";

export const SEARCH_CHANNEL = "SEARCH_CHANNEL";
// Playlist
export const BROWSE_VIDEO_PLAYLIST = "BROWSE_VIDEO_PLAYLIST";

export const LIKE_VIDEO_PLAYLIST_SUCCESS = "LIKE_VIDEO_PLAYLIST_SUCCESS";
export const LIKE_VIDEO_PLAYLIST_FAIL = "LIKE_VIDEO_PLAYLIST_FAIL";

export const UNLIKE_VIDEO_PLAYLIST_SUCCESS = "UNLIKE_VIDEO_PLAYLIST_SUCCESS";
export const UNLIKE_VIDEO_PLAYLIST_FAIL = "UNLIKE_VIDEO_PLAYLIST_FAIL";

export const FAVOURITE_VIDEO_PLAYLIST_SUCCESS =
  "FAVOURITE_VIDEO_PLAYLIST_SUCCESS";
export const FAVOURITE_VIDEO_PLAYLIST_FAIL = "FAVOURITE_VIDEO_PLAYLIST_FAIL";

export const VIEW_VIDEO_PLAYLIST = "VIEW_VIDEO_PLAYLIST";

export const EDIT_VIDEO_PLAYLIST_SUCCESS = "EDIT_VIDEO_PLAYLIST_SUCCESS";
export const EDIT_VIDEO_PLAYLIST_FAIL = "EDIT_VIDEO_PLAYLIST_FAIL";

export const DELETE_VIDEO_PLAYLIST = "DELETE_VIDEO_PLAYLIST";
// Artist
export const BROWSE_ARTIST_VIDEO = "BROWSE_ARTIST_VIDEO";

export const FAVOURITE_ARTIST_VIDEO_SUCCESS = "FAVOURITE_ARTIST_VIDEO_SUCCESS";
export const FAVOURITE_ARTIST_VIDEO_FAIL = "FAVOURITE_ARTIST_VIDEO_FAIL";

export const ARTIST_VIDEOS = "ARTIST_VIDEOS";
// Manage
export const MY_VIDEOS = "MY_VIDEOS";

export const MY_CHANNEL_VIDEOS = "MY_CHANNEL_VIDEOS";

export const MY_CHANNEL_PLAYLISTS = "MY_CHANNEL_PLAYLISTS";
// Category
export const VIDEOS_SELECTED_CATEGORY = "VIDEOS_SELECTED_CATEGORY";
export const VIDEO_CATEGORY = "VIDEO_CATEGORY";

// Music
// Album
export const BROWSE_MUSIC_ALBUM = "BROWSE_MUSIC_ALBUM";

export const RATE_MUSIC_ALBUM_SUCCESS = "RATE_MUSIC_ALBUM_SUCCESS";
export const RATE_MUSIC_ALBUM_FAIL = "RATE_MUSIC_ALBUM_FAIL";

export const LIKE_MUSIC_ALBUM_SUCCESS = "LIKE_MUSIC_ALBUM_SUCCESS";
export const LIKE_MUSIC_ALBUM_FAIL = "LIKE_MUSIC_ALBUM_FAIL";

export const FAVOURITE_MUSIC_ALBUM_SUCCESS = "FAVOURITE_MUSIC_ALBUM_SUCCESS";
export const FAVOURITE_MUSIC_ALBUM_FAIL = "FAVOURITE_MUSIC_ALBUM_FAIL";

export const ADD_TO_PLAYLIST_MUSIC_SUCCESS = "ADD_TO_PLAYLIST_MUSIC_SUCCESS";
export const ADD_TO_PLAYLIST_MUSIC_FAIL = "ADD_TO_PLAYLIST_MUSIC_FAIL";

export const VIEW_MUSIC_ALBUM = "VIEW_MUSIC_ALBUM";

export const MUSIC_ALBUM_COMMENT = "MUSIC_ALBUM_COMMENT";

export const SEARCH_MUSIC_ALBUM = "SEARCH_MUSIC_ALBUM";
// Songs
export const BROWSE_SONGS = "BROWSE_SONGS";

export const SONGS_COMMENT_SUCCESS = "SONGS_COMMENT_SUCCESS";
export const SONGS_COMMENT_FAIL = "SONGS_COMMENT_FAIL";

export const LIKE_SONGS_SUCCESS = "LIKE_SONGS_SUCCESS";
export const LIKE_SONGS_FAIL = "LIKE_SONGS_FAIL";

export const FAVOURITE_SONGS_SUCCESS = "FAVOURITE_SONGS_SUCCESS";
export const FAVOURITE_SONGS_FAIL = "FAVOURITE_SONGS_FAIL";

export const ALL_SONGS_COMMENT = "ALL_SONGS_COMMENT";

export const ADD_TO_PLAYLIST_SONGS_SUCCESS = "ADD_TO_PLAYLIST_SONGS_SUCCESS";
export const ADD_TO_PLAYLIST_SONGS_FAIL = "ADD_TO_PLAYLIST_SONGS_FAIL";

export const SONGS_LYRICS = "SONGS_LYRICS";

export const SEARCH_SONGS = "SEARCH_SONGS";
// Playlist
export const BROWSE_MUSIC_PLAYLIST = "BROWSE_MUSIC_PLAYLIST";

export const VIEW_MUSIC_PLAYLIST = "VIEW_MUSIC_PLAYLIST";

export const FAVOURITE_MUSIC_PLAYLIST_SUCCESS =
  "FAVOURITE_MUSIC_PLAYLIST_SUCCESS";
export const FAVOURITE_MUSIC_PLAYLIST_FAIL = "FAVOURITE_MUSIC_PLAYLIST_FAIL";

export const EDIT_MUSIC_PLAYLIST_SUCCESS = "EDIT_MUSIC_PLAYLIST_SUCCESS";
export const EDIT_MUSIC_PLAYLIST_FAIL = "EDIT_MUSIC_PLAYLIST_FAIL";

export const SEARCH_MUSIC_PLAYLIST = "SEARCH_MUSIC_PLAYLIST";
// Artist
export const BROWSE_ARTIST_MUSIC = "BROWSE_ARTIST_MUSIC";

export const VIEW_ARTIST_MUSIC = "VIEW_ARTIST_MUSIC";
// Manage
export const MY_MUSIC_ALBUMS = "MY_MUSIC_ALBUMS";

export const MY_MUSIC_PLAYLISTS = "MY_MUSIC_PLAYLISTS";

export const DELETE_PLAYLIST = "DELETE_PLAYLIST";

// Articles
export const BROWSE_ARTICLES = "BROWSE_ARTICLES";

export const LIKE_ARTICLE_SUCCESS = "LIKE_ARTICLE_SUCCESS";
export const LIKE_ARTICLE_FAIL = "LIKE_ARTICLE_FAIL";

export const UNLIKE_ARTICLE_SUCCESS = "UNLIKE_ARTICLE_SUCCESS";
export const UNLIKE_ARTICLE_FAIL = "UNLIKE_ARTICLE_FAIL";

export const FAVOURITE_ARTICLE_SUCCESS = "FAVOURITE_ARTICLE_SUCCESS";
export const FAVOURITE_ARTICLE_FAIL = "FAVOURITE_ARTICLE_FAIL";

export const ARTICLE_COMMENT_SUCCESS = "ARTICLE_COMMENT_SUCCESS";
export const ARTICLE_COMMENT_FAIL = "ARTICLE_COMMENT_FAIL";

export const VIEW_ARTICLE = "VIEW_ARTICLE";

export const ALL_ARTICLE_COMMENT = "ALL_ARTICLE_COMMENT";

export const ARTICLE_CATEGORIES = "ARTICLE_CATEGORIES";

export const VIEW_ARTICLE_CATEGORY = "VIEW_ARTICLE_CATEGORY";

export const MY_ARTICLE = "MY_ARTICLE";

export const EDIT_ARTICLE_SUCCESS = "EDIT_ARTICLE_SUCCESS";
export const EDIT_ARTICLE_FAIL = "EDIT_ARTICLE_FAIL";

export const CREATE_ARTICLE_SUCCESS = "CREATE_ARTICLE_SUCCESS";
export const CREATE_ARTICLE_FAIL = "CREATE_ARTICLE_FAIL";

export const DELETE_ARTICLE = "DELETE_ARTICLE";

// Prayers
export const BROWSE_PRAYERS = "BROWSE_PRAYERS";

export const LIKE_PRAYER_SUCCESS = "LIKE_PRAYER_SUCCESS";
export const LIKE_PRAYER_FAIL = "LIKE_PRAYER_FAIL";

export const UNLIKE_PRAYER_SUCCESS = "UNLIKE_PRAYER_SUCCESS";
export const UNLIKE_PRAYER_FAIL = "UNLIKE_PRAYER_FAIL";

export const SEARCH_PRAYER = "SEARCH_PRAYER";

export const PRAYER_CATEGORIES = "PRAYER_CATEGORIES";

export const VIEW_PRAYER = "VIEW_PRAYER";

export const PRAYER_COMMENT_SUCCESS = "PRAYER_COMMENT_SUCCESS";
export const PRAYER_COMMENT_FAIL = "PRAYER_COMMENT_FAIL";

export const MY_PRAYER = "MY_PRAYER";

export const EDIT_PRAYER_SUCCESS = "EDIT_PRAYER_SUCCESS";
export const EDIT_PRAYER_FAIL = "EDIT_PRAYER_FAIL";

export const CREATE_PRAYER_SUCCESS = "CREATE_PRAYER_SUCCESS";
export const CREATE_PRAYER_FAIL = "CREATE_PRAYER_FAIL";

export const DELETE_PRAYER = "DELETE_PRAYER";

// Settings
export const GET_SETTINGS = "GET_SETTINGS";

export const SHOW_PRIVACY = "SHOW_PRIVACY";

export const SHOW_TERMS_CONDITIIONS = "SHOW_TERMS_CONDITIIONS";

export const EDIT_PROFILE_SUCCESS = "EDIT_PROFILE_SUCCESS";
export const EDIT_PROFILE_FAIL = "EDIT_PROFILE_FAIL";
// General
export const GENERAL_FORM_SUCCESS = "GENERAL_FORM_SUCCESS";
export const GENERAL_FORM_FAIL = "GENERAL_FORM_FAIL";
// Privacy
export const PRIVACY_FORM_SUCCESS = "PRIVACY_FORM_SUCCESS";
export const PRIVACY_FORM_FAIL = "PRIVACY_FORM_FAIL";
// Networks
export const ALL_JOINED_NETWORK = "ALL_JOINED_NETWORK";

export const AVAILABLE_NETWORK = "AVAILABLE_NETWORK";

export const LEAVE_NETWORK = "LEAVE_NETWORK";

export const JOIN_NETWORK_SUCCESS = "JOIN_NETWORK_SUCCESS";
export const JOIN_NETWORK_FAIL = "JOIN_NETWORK_FAIL";
// Notifications
export const NOTIFICATION_FORM_SUCCESS = "NOTIFICATION_FORM_SUCCESS";
export const NOTIFICATION_FORM_FAIL = "NOTIFICATION_FORM_FAIL";
// Password
export const PASSWORD_FORM_SUCCESS = "PASSWORD_FORM_SUCCESS";
export const PASSWORD_FORM_FAIL = "PASSWORD_FORM_FAIL";

// Search
export const CORE_SEARCH = "CORE_SEARCH";

export const FILTER_SEARCH_SUCCESS = "FILTER_SEARCH_SUCCESS";
export const FILTER_SEARCH_FAIL = "FILTER_SEARCH_FAIL";

// Common
export const SUBCATEGORY_SUCCESS = "SUBCATEGORY_SUCCESS";
export const SUBCATEGORY_FAIL = "SUBCATEGORY_FAIL";

export const SUB_SUBCATEGORY_SUCCESS = "SUB_SUBCATEGORY_SUCCESS";
export const SUB_SUBCATEGORY_FAIL = "SUB_SUBCATEGORY_FAIL";

export const SUBMIT_REPORT_SUCCESS = "SUBMIT_REPORT_SUCCESS";
export const SUBMIT_REPORT_FAIL = "SUBMIT_REPORT_FAIL";

export const CONTENT_FAVOURITE_SUCCESS = "CONTENT_FAVOURITE_SUCCESS";
export const CONTENT_FAVOURITE_FAIL = "CONTENT_FAVOURITE_FAIL";

export const LIKED_ALBUM_SUCCESS = "LIKED_ALBUM_SUCCESS";
export const LIKED_ALBUM_FAIL = "LIKED_ALBUM_FAIL";

export const ALBUM_COMMNET_LIKE_SUCCESS = "ALBUM_COMMNET_LIKE_SUCCESS";
export const ALBUM_COMMNET_LIKE_FAIL = "ALBUM_COMMNET_LIKE_FAIL";

export const SHARE_ON_FEED_SUCCESS = "SHARE_ON_FEED_SUCCESS";
export const SHARE_ON_FEED_FAIL = "SHARE_ON_FEED_FAIL";

// Event
export const BROWSE_EVENT = "BROWSE_EVENT";

export const MY_EVENT = "MY_EVENT";

export const CREATE_EVENT_SUCCESS = "CREATE_EVENT_SUCCESS";
export const CREATE_EVENT_FAIL = "CREATE_EVENT_FAIL";

export const DELETE_EVENT = "DELETE_EVENT";

export const EVENT_MENU = "EVENT_MENU";

export const CATEGORIES_EVENTS = "CATEGORIES_EVENTS";

export const FAVOURITE_EVENTS_SUCCESS = "FAVOURITE_EVE  NTS_SUCCESS";
export const FAVOURITE_EVENTS_FAIL = "FAVOURITE_EVENTS_SUCCESS";

export const VIEW_EVENT = "VIEW_EVENT";

export const EVENT_INFORMATION = "EVENT_INFORMATION";

export const LEAVE_EVENT_SUCCESS = "LEAVE_EVENT_SUCCESS";
export const LEAVE_EVENT_FAIL = "LEAVE_EVENT_FAIL";

export const EDIT_EVENT_SUCCESS = "EDIT_EVENT_SUCCESS";
export const EDIT_EVENT_FAIL = "EDIT_EVENT_FAIL";

// Page
export const BROWSE_PAGES = "BROWSE_PAGES";

export const CREATE_PAGE_SUCCESS = "CREATE_PAGE_SUCCESS";
export const CREATE_PAGE_FAIL = "CREATE_PAGE_FAIL";

export const DELETE_PAGE = "DELETE_PAGE";

export const PAGE_MENU = "PAGE_MENU";

export const LIKE_PAGE_SUCCESS = "LIKE_PAGE_SUCCESS";
export const LIKE_PAGE_FAIL = "LIKE_PAGE_FAIL";

export const VIEW_PAGE = "VIEW_PAGE";

export const CATEGORIES_PAGES = "CATEGORIES_PAGES";

export const FOLLOW_PAGES_SUCCESS = "FOLLOW_PAGES_SUCCESS";
export const FOLLOW_PAGES_FAIL = "FOLLOW_PAGES_FAIL";

export const PAGE_INFORMATION = "PAGE_INFORMATION";

export const LEAVE_PAGE_SUCCESS = "LEAVE_PAGE_SUCCESS";
export const LEAVE_PAGE_FAIL = "LEAVE_PAGE_FAIL";

export const EDIT_PAGE_SUCCESS = "EDIT_PAGE_SUCCESS";
export const EDIT_PAGE_FAIL = "EDIT_PAGE_FAIL";

export const MANAGE_PAGE_SUCCESS = "MANAGE_PAGE_SUCCESS";
export const MANAGE_PAGE_FAIL = "MANAGE_PAGE_FAIL";

export const PAGE_MEMBER = "PAGE_MEMBER";

// Contest
export const BROWSE_CONTEST = "BROWSE_CONTEST";

export const CREATE_CONTEST_SUCCESS = "CREATE_CONTEST_SUCCESS";
export const CREATE_CONTEST_FAIL = "CREATE_CONTEST_FAIL";

export const DELETE_CONTEST = "DELETE_CONTEST";

export const CONTEST_MENU = "CONTEST_MENU";

export const FAVOURITE_CONTESTS_SUCCESS = "FAVOURITE_EVE  NTS_SUCCESS";
export const FAVOURITE_CONTESTS_FAIL = "FAVOURITE_CONTESTS_SUCCESS";

export const VIEW_CONTEST = "VIEW_CONTEST";

export const CATEGORIES_CONTESTS = "CATEGORIES_CONTESTS";

export const EDIT_CONTEST_SUCCESS = "EDIT_CONTEST_SUCCESS";
export const EDIT_CONTEST_FAIL = "EDIT_CONTEST_FAIL";

export const LEAVE_CONTEST_SUCCESS = "LEAVE_CONTEST_SUCCESS";
export const LEAVE_CONTEST_FAIL = "LEAVE_CONTEST_FAIL";

export const LIKE_CONTEST_SUCCESS = "LIKE_CONTEST_SUCCESS";
export const LIKE_CONTEST_FAIL = "LIKE_CONTEST_FAIL";

// Business
export const BROWSE_BUSINESS = "BROWSE_BUSINESS";

export const CREATE_BUSINESS_SUCCESS = "CREATE_BUSINESS_SUCCESS";
export const CREATE_BUSINESS_FAIL = "CREATE_BUSINESS_FAIL";

export const DELETE_BUSINESS = "DELETE_BUSINESS";

export const BUSINESS_MENU = "BUSINESS_MENU";

export const FAVOURITE_BUSINESSS_SUCCESS = "FAVOURITE_EVE  NTS_SUCCESS";
export const FAVOURITE_BUSINESSS_FAIL = "FAVOURITE_BUSINESSS_SUCCESS";

export const VIEW_BUSINESS = "VIEW_BUSINESS";

export const CATEGORIES_BUSINESSS = "CATEGORIES_BUSINESSS";

export const EDIT_BUSINESS_SUCCESS = "EDIT_BUSINESS_SUCCESS";
export const EDIT_BUSINESS_FAIL = "EDIT_BUSINESS_FAIL";

export const BUSINESS_INFORMATION = "BUSINESS_INFORMATION";

export const BUSINESS_MEMBER = "BUSINESS_MEMBER";

export const LIKE_BUSINESS_SUCCESS = "LIKE_BUSINESS_SUCCESS";
export const LIKE_BUSINESS_FAIL = "LIKE_BUSINESS_FAIL";

export const BUSINESS_FOLLOW_SUCCESS = "BUSINESS_FOLLOW_SUCCESS";
export const BUSINESS_FOLLOW_FAIL = "BUSINESS_FOLLOW_FAIL";
